apiVersion: v1
kind: ConfigMap
metadata:
  name: actualbudget-backup-config
  namespace: actualbudget
  labels:
    app.kubernetes.io/name: actualbudget
    app.kubernetes.io/component: backup
    app.kubernetes.io/part-of: homelab
data:
  CONTAINER_NAME: "actualbudget-backups"
  BACKUP_RETENTION_COUNT: "8"
  BACKUP_PREFIX: "actualbudget-backup"
