apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/actualbudget
  - certificate.yaml
  - backup-cronjob.yaml
  - backup-script-configmap.yaml
  - backup-config-configmap.yaml
  - backup-externalsecret.yaml