apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base/airflow
- database-externalsecret.yaml
- salesforce-credentials-externalsecret.yaml
- postgres-credentials-externalsecret.yaml
- certificate.yaml
