apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: airflow

resources:
- ../../base/airflow
- salesforce-credentials-externalsecret.yaml
- postgres-credentials-externalsecret.yaml
- certificate.yaml
- database-externalsecret.yaml

patches:
- path: release-patch.yaml
  target:
    kind: HelmRelease
    name: airflow

